README.md

We still mention the old "pensieve" name in `README.md`.

Change reference to pensieve in README

---

setup.py

To avoid having to rely on a debug interpreter that doesn't define
`NDEBUG`, ensure we undefine it if we are in a test build. This allows
us to trigger asserts in test builds reliably.

Undefine NDEBUG in test builds

---

src/memray/_memray/elf_shenanigans.cpp
src/memray/_memray/elf_utils.h

The PLT/Jump table can have different entry types depending on the phase
of the moon, the position of the planets, the current weather and other
unpredictable stuff. Normally x86_64 uses RELA entries, and x86 uses REL
entries. But sometimes it doesn't happen, so we need to check the
DT_PLTREL tag to see which one we should use at runtime.
This method is more reliable than assuming that 64 bits means RELA and
32 bits mean REL.

Don't rely on architecture information to get the type of the PLT table

---

README.md
docs/live.rst
src/memray/commands/__init__.py

Originally, the --live option required to connect separately to the
process in another terminal but this was changed to start the process in
the background automatically and attach in the foreground. The old
behavior was renamed to be --live-remote but the documentation was never
updated to reflect this.

Update the live docs to account for the new --live-remote option

---

.gitignore
setup.py
src/memray/_memray/elf_shenanigans.cpp
src/memray/_memray/hooks.cpp
src/memray/_memray/hooks.h
src/memray/_memray/logging.h
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h

We missed a few places where the old name was used as part of a longer
string.

Update the package name everywhere

---

src/memray/_memray.pyx
src/memray/_memray_test_utils.pyx
tests/integration/test_socket.py
tests/integration/test_tracing.py

Cython correctly uses the name and line numbers from the included file
when profiling is enabled, so by moving these into a dedicated file that
won't need to change very often, we can avoid needing to change the line
numbers in `test_tracing.py` as often.

Split test utilities into a separate .pyx file

---

README.md
docs/flamegraph.rst
docs/run.rst
docs/stats.rst
docs/summary.rst
docs/table.rst
docs/tree.rst
setup.py

Closes: #12
Currently we only have `memray3.X` as an entry point but having also
`memray` as an entry point will make it easier for people with only one
Python version installed and it would make the usage examples from -h
line up with how we actually expect it to be used.
This commit also updates the docs and the README file to simplify the
examples with the new entry point.

Add a `memray` entry point

---

README.md
src/memray/commands/__init__.py

As stated in https://github.com/bloomberg/memray/issues/46, `-o` should come after `run`, and not after the script. This PR fixes that in README and the `__init__` file.
cc @pablogsal

DOC fix -o position

---

Makefile

Closes: #30
When we build the distribution without "--wheel", `build_ext` gets
called during "python -m build" from the temporary build directory,
while with "--wheel" the files built during "make build" are copied into
the created wheel. This allows the build to be more reproducible as in
this way the DWARF included in the extension to not change due to the
temporary directory path being part of it.

Add `--wheel` to the `make dist` target

---

.github/workflows/sanity-check.yml

To avoud having to manually mention the DCO to contributors and to make
sure we don't forget to check that all contributors include the
sign-off, add a check to the CI that ensures that this is enforced.
Closes: #41

Add a check for the DCO in the CI

---

Dockerfile

Use the VIRTUAL_ENV environment variable inside the Dockerfile to define the PYTHON variable
if VIRTUAL_ENV changes it will be automatically reflected in the PYTHON binary

Use VIRTUAL_ENV variable for python binary

---

README.md
docs/api.rst
docs/conf.py
docs/index.rst
docs/run.rst
src/memray/_destination.py
src/memray/_memray.pyi
src/memray/_memray.pyx
src/memray/_memray/sink.cpp
src/memray/_memray/sink.h
src/memray/_memray/sink.pxd
src/memray/commands/common.py
src/memray/commands/run.py
tests/integration/test_api.py
tests/integration/test_socket.py
tests/unit/test_cli.py
tests/unit/test_highwatermark_command.py

Closes: #25 
Rendered documentation can be previewed [here](https://godlygeek.github.io/memray/api.html).
@pablogsal Let me know whether there's anything else that you'd like to see documented here. 
Now is probably our last chance to rename some of this before the API actually gets users. I'm wondering whether we should have gone with `force=True` or `overwrite=True` for the parameter to tell a `FileDestination` to overwrite an existing file, instead of `exist_ok=True`. I'm also thinking that the name `SocketDestination` is a bit odd for something that configures how to start a _server_, rather than a _client_...

Finalize and document Tracker API

---

src/memray/_memray/hooks.h
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_reader.h
src/memray/_memray/records.cpp
src/memray/_memray/records.h
src/memray/_memray/snapshot.cpp
src/memray/_memray/tracking_api.cpp
tests/integration/test_main.py

Here are a bunch of optimizations that reduce the result file size by 20%:
- Reduce file size in non-native mode by specializing native allocations
- Ensure our enumerations only use the size of a char

Reduce result file size by 20% in non-native mode

---

src/memray/_memray/record_writer.h

When we split off `ALLOCATION_WITH_NATIVE` from `ALLOCATION`, we missed
a spot that needed to be updated to keep an accurate count of the total
number of allocation-ish records.

Fix allocation count in header record

---

src/memray/_memray.pyx
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_reader.h
src/memray/_memray/record_reader.pxd
src/memray/_memray/snapshot.pxd
src/memray/_memray/source.cpp

Instead, read the file twice. The first time through, collect the memory
records and find the high water mark. After that, the user can choose to
do a pass that actually yields allocation records.
Note that with this design it no longer makes sense to warn if the input
file was closed before we reached EOF, since now that's a normal
consequence of retrieving the high water mark allocations: the second
pass over the file closes it once it has read up through the high water
mark index.
Closes: #43

Decode capture files in two passes

---

README.md
docs/api.rst
docs/flamegraph.rst
docs/python_allocators.rst
docs/run.rst
docs/stats.rst
docs/tree.rst
src/memray/commands/__init__.py
src/memray/commands/flamegraph.py
src/memray/commands/live.py
src/memray/commands/parse.py
src/memray/commands/table.py
src/memray/commands/tree.py

NO#
DOC: a few typos and a Linux badge.
Works in HTML view
Added in PyConUS2022's sprints for testing purposes.

docs: Add a Linux badge and fix typos and grammar

---

docs/flamegraph.rst

I'm proposing a quickfix for the documentation.
As reading the documention to memray flamegraphs
https://bloomberg.github.io/memray/flamegraph.html
I consider the information that says that the graph shows the second biggest memory consumption going from function `a()` is not correct as the `a()`[1] does not allocates the memory. The second biggest memory allocator should be `e()`.
[1]
```
def a(n):
return [b(n), h(n)]
```

Adjusting docs flamegraph description to follow the depicted graph

---

src/memray/commands/run.py
tests/integration/test_main.py
tests/unit/test_cli.py

Hi, this closes #44.
can now run: 
- `memray run -c 'print("my python commands")'`  -> a py file will be created with this string as its content. then `arg.script` will be replaced with this file's name. after that, memray runs as before.
- `memray run -c <my_file>.py` -> parser.error with help message to remove `-c` option
(EDIT: no longer creating a file)

Add `-c` option: program passed as string

---

src/memray/_memray/hooks.h

Rather than defining the entire list of hooked functions twice, have one
platforms-specific list, and then append it to a base list that's common
across all platforms.
I thought I had pushed this to the #75 branch, but I guess I forgot to!

Remove duplication in hooks X-macro definition

---

src/memray/_memray/record_writer.h
tests/integration/test_tracing.py

Fix a bug introduced in:
d168b0a Store count of frames to pop in FRAME_POP flags
which fortunately never made it into a released version. That commit
changed our tracker to pack the number of frames being popped into
a bit field, and handle the case where the number of frames to pop was
too large for the bit field by looping and emitting multiple records.
But, the check to see whether the number of frames to pop was too large
for the bit field was incorrect - the bit field is only 4 bits wide, and
so can only hold a maximum value of 15, not 63.

Fix popping more than 16 frames with `popFrames`

---

.github/workflows/build.yml
Dockerfile
README.md
pyproject.toml
setup.py
src/memray/_destination.py
src/memray/_memray.pyx
src/memray/_memray/lz4_stream.h
src/memray/_memray/sink.cpp
src/memray/_memray/sink.h
src/memray/_memray/sink.pxd
src/memray/_memray/source.cpp
src/memray/_memray/source.h
src/memray/commands/run.py
tests/unit/test_reader.py

- Vendor a copy of lz4 stream
- Update the `FileSink` and `FileSource` to use `lz4`
- Update project files to account for the dependency on `lz4`
As a bonus, this seem to make the reader 5% faster:
```
Benchmark 1: memray parse /tmp/lel.bin  > /dev/null
Time (mean ± σ):      1.051 s ±  0.018 s    [User: 1.023 s, System: 0.026 s]
Range (min … max):    1.016 s …  1.081 s    10 runs
Benchmark 1: memray parse /tmp/lel2.bin  > /dev/null
Time (mean ± σ):     990.6 ms ±   9.5 ms    [User: 968.2 ms, System: 21.5 ms]
Range (min … max):   969.1 ms … 999.5 ms    10 runs
```

Leverage lz4 to add file compression on the boundaries

---

tests/integration/test_processes.py

The `pytest-cov` plugin doesn't support `multiprocessing.Pool.__exit__`.
They suggest using `Pool.close()` and `Pool.join()` instead, but that's
not an option here - what we're testing is our own behavior when the
pool is terminated, and so using `Pool.close()` and `Pool.join()` would
defeat at least one of the goals of these tests.
We may be able to solve this some other way, but for now, just disable
coverage analysis for these tests to fix our CI flakiness.

tests: Disable coverage on multiprocessing tests

---

.github/workflows/build.yml
setup.py
valgrind.supp

This seems to achieve some minor tracking speedups on the order of 2%.

Use LTO and hide our symbols

---

docs/python_allocators.rst
docs/run.rst
news/92.feature.rst
src/memray/_memray.pyi
src/memray/_memray.pyx
src/memray/_memray/alloc.pxd
src/memray/_memray/hooks.cpp
src/memray/_memray/hooks.h
src/memray/_memray/record_reader.cpp
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd
src/memray/_memray_test_utils.pyx
src/memray/_test.py
src/memray/commands/run.py
tests/integration/test_processes.py
tests/integration/test_tracing.py
tests/integration/test_tracking.py
tests/unit/test_cli.py
tests/utils.py

The Python allocators don't generally generate allocation events to the
system allocator. This is how Python normally runs and is directly
responsible of keeping it fast and this translates to profiling as well.
Sometimes, users may still be interested on the requests that the
interpreter does to the Python allocators and although this generates a
lot more data and makes profiling slower, it may help in some
situations. This acts also as an alternative way to run with
`PYTHONMALLOC=malloc` but without collating the data with the system
allocator.

Allow tracing the Python allocators

---

src/memray/commands/run.py
tests/integration/test_main.py

Hi, this closes #76.
- refactor suggestion to `test_cli.py::TestRunSubCommand` (class level mocks limited testing possibilities)
- added test that fails when not editing sys.path
- added method `edit_sys` that edits sys.path (also moved existing sys edits to it). 
sys.path[0] will be the directory containing args.script, or `'.'` when `run -c` (like python does)

Update `sys.path` when running `memray run`

---

setup.py
tests/unit/test_summary_reporter.py
tests/unit/test_tui_reporter.py

Rich introduced some formatting changes in version 11.0.0 and we pinned
the version so the test suite didn't break with the new formatting.
There is really no reason other than this why we couldn't run with a
newer version and we are missing a bunch of general improvements in the
library.
This commit updates the test suite to cope with the new formatting in
the latest versions of `rich`.

Uodate the test suite to the latest version of 'rich'

---

src/memray/commands/run.py

`sphinx-argparse` wanted to document `--no-compress` as having a default
value of `True`, which isn't correct. I think it's confused by the fact
that `--no-compress` has a `dest="compress_on_exit"`, which another
argument sets up with `default=True`.
Regardless, the reason we gave these things different names was so that
we could support multiple different compression options in the future.
Pre-factor this into a mutually exclusive group of compression related
options, and have `--no-compress` toggle off the one that defaults
to `True`. We would have needed to do something like this in the future
if we ever added another compression option, and this gets the Sphinx
docs looking the way we want now.

Improve the docs for `--no-compress`

---

news/95.bugfix.rst
src/memray/reporters/stats.py
tests/unit/test_stats_reporter.py

Signed-off-by: Jingkai Tan <tjingkai@bloomberg.net>
Fixes #84.
Cap the known valid range to ensure that anything greater than the second to last bucket will appear in the last bucket.
Ensured that output is as expected (missing mmap allocation shows up)
```
🕙12:30:27 ❯ memray stats output.bin
📏 Total allocations:
9
📦 Total memory allocated:
9.313GB
📊 Histogram of allocation size:
min: 536.000B
----------------------------------------
< 2.792KB  : 4 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
< 14.895KB : 1 ▇▇▇▇▇▇▇
< 79.453KB : 0
< 423.837KB: 0
< 2.208MB  : 0
< 11.778MB : 0
< 62.827MB : 0
< 335.145MB: 0
< 1.746GB  : 0
<=9.313GB  : 1 ▇▇▇▇▇▇▇
----------------------------------------
max: 9.313GB
📂 Allocator type distribution:
MALLOC: 5
MMAP: 1
🥇 Top 5 largest …
```

Fix missing allocations in `memray stats` histogram

---

docs/index.rst
docs/licenses.rst

This page list the licenses of all of the open source libraries that
we're either modifying or statically linking in.

docs: Add a Licenses page

---

setup.py

Remove vendored libbacktrace from our built wheel. Using `find_namespace_packages` instead of `find_packages` results in
`src/vendor/` being picked up as a namespace package called `vendor` and included in the wheel that we build. This is only needed at build time, and shouldn't be installed.
Also, remove `package_data` from our `setuptools.setup()` call. This is redundant, as we're already providing `include_package_data=True`, which includes every data file listed in the manifest, including `py.typed`.

Exclude libbacktrace from our built wheel

---

src/memray/_memray/tracking_api.h

*Issue number of the reported bug or feature request: #51*
Remove inline attribute from exact_unwind()
Compiled and ran a simple test on a ppc64le machine.

Avoid inlining `exact_unwind`

---

news/117.bugfix.rst
src/memray/_memray/sink.cpp

Previously we were using lseek + write to grow our capture files, but
that resulted in SIGBUS being raised when a disk had filled up, rather
than an error code being returned (since it created sparse files that
would actually grow to require more disk space only as we `memcpy`'d
data into our memory-mapped array.
Instead, use `posix_fallocate` to grow our capture file. As long as this
call succeeds, it is guaranteed that future copies into our memory
mapped array will succeed.
Closes #116

Grow capture files with `posix_fallocate`

---

NEWS.rst
docs/python_allocators.rst
docs/run.rst

*Issue number of the reported bug or feature request: #121*
The docs said `--track-python-allocators`, the cli supports `--trace-python-allocators`. Now they agree.
closes #121

Fix inconsistency in cli documentation regarding --trace-python-allocators 

---

news/133.bugfix.rst
src/memray/reporters/stats.py
tests/unit/test_stats_reporter.py

Previously we potentially chose a very large step, which resulted in
crazy bucket sizes.
Relates-to: #130

Fix histogram when all allocations are the same size

---

news/129.bugfix.rst
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_writer.cpp
src/memray/_memray/record_writer.h
src/memray/_memray/records.h
src/memray/_memray/source.cpp
src/memray/_memray/source.h
src/memray/_memray/tracking_api.cpp
tests/integration/test_main.py

Make the `RecordWriter` finish a capture file by writing a non-zero
trailer byte that the `RecordReader` will ignore. When the `FileSource`
reads a (non-compressed) capture file, have it ignore any trailing zero
bytes without returning them to the caller. If the caller attempts to
read into them, treat it as though EOF has been reached instead.
When a trailer byte is encountered by the reader, treat it as EOF,
rather than continuing to request bytes from the reader.

Recognize and handle truncated capture files

---

src/memray/_memray/record_reader.h
src/memray/_memray/records.h
src/memray/_memray/tracking_api.h

Previously these were able to start at an arbitrary user-controlled
number and count up by an arbitrary user-controlled number, but we're no
longer leveraging that feature for anything, so we can drop the
complexity.

Make frame IDs start at 0 and count up by 1

---

news/147.bugfix.1.rst
news/147.bugfix.2.rst
news/147.bugfix.3.rst
src/memray/_memray/record_writer.h
src/memray/_memray/sink.h
src/memray/commands/run.py
src/memray/reporters/tui.py
tests/unit/test_cli.py
tests/unit/test_tui_reporter.py

Closes #143 
Closes #145
Closes #146

Fix several live mode bugs

---

news/141.bugfix.rst
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
valgrind.supp

Seems that libunwind just chokes if the function that calls unw_get_reg
is not inlined in aarch64. Additionally, there are some problems with
inlined functions that call libunwind's APIs in powerpc and other
architectures.
To avoid all this trouble, leverage just the fast unwinding APIs, which
will make the program counters more consistent and will eliminate the
inline shenanigans.
Closes: https://github.com/bloomberg/memray/issues/126

Always leverage fast unwinding to obtain the native stack

---

docs/stats.rst
news/136.bugfix.1.rst
news/136.bugfix.2.rst
news/136.bugfix.3.rst
news/136.bugfix.4.rst
news/136.bugfix.5.rst
news/136.feature.rst
news/136.removal.rst
src/memray/_memray.pyi
src/memray/_memray.pyx
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_reader.h
src/memray/_memray/record_reader.pxd
src/memray/_memray/records.pxd
src/memray/_memray/snapshot.cpp
src/memray/_memray/snapshot.h
src/memray/_memray/snapshot.pxd
src/memray/_stats.py
src/memray/_stats.pyi
src/memray/commands/stats.py
src/memray/reporters/stats.py
tests/unit/test_stats_reporter.py

Remove the `--include-all-allocations` / `-a` option for the `stats`
reporter and have it process all allocations by default. Its default
behavior of only processing allocations that made up the high water mark
of the application's memory usage was confusing and misleading.
Previously when `-a` was provided, deallocations with `free` and
`munmap` were included in the reported count of "Total allocations".
This has been fixed.
Similarly, when `-a` was provided, memory freed by `munmap` (though not
`free`) was incorrectly being added to the count of total memory
allocated. This has been fixed.
The histogram has been fixed to work on the actual sizes of all
allocations. Previously it only saw the sizes after a rollup by stack
had already been performed, and it was therefore binning …

Fix many bugs in the stats reporter

---

src/memray/_memray/records.h
tests/integration/test_tracking.py

Due to how we handle trailing 0 in files, if a file has no allocations
we will fail correctly reading the Python allocator as currently is 4
bytes, but the last 3 are always 0. If there aren't any other records
after it we will incorrectly invalidate all trailing zeroes, which will
fail reading the Python allocator.
This technically requires a more complex fix, but for now we can make
a simple change and make the Python allocator 1 byte, which will not
suffer from this problem.

Ensure we can read a file with no allocations

---

setup.py

This is the earliest version to support `Progress.get_default_columns`.
Closes #156

Require rich >= 11.2.0

---

src/memray/commands/run.py

We want to tell the user that they're doing the wrong thing if they do
`memray run -c foo.py`, but that check can fail with `ENAMETOOLONG` if
the argument given to `-c` is too long to possibly be a file path.
Just ignore any OS error that occurs when doing this check, since this
check is just a nice-to-have anyway, to provide a nice error message for
something that would have gone on to fail anyway.

Ignore ENAMETOOLONG in checking if `-c` is a file

---

src/memray/_memray/tracking_api.cpp

In an initial implementation of this function `code` was an owned
reference and needed to be decref'd, but in the final version it's
a borrowed reference and must not be decref'd. This went unnoticed
because the bug is on an error path that we never hit.

Remove a decref of a borrowed reference

---

.github/workflows/build.yml

We are testing multiple Python versions twice: once when building wheels
and another in a target in the main CI. The only thing this target
can give us more than the tests that are being executed as part of the
wheels is to run the test suite under "pycoverage".
To simplify the setup, just run coverage under the latest Python version
in the main CI, as there is not (currently) anything version-specific.

Simplify the CI

---

news/176.bugfix.rst
src/memray/_memray.pyx
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd
tests/integration/test_tracing.py

Previously, we would retain references to frames that were on the stack
in a given thread, but without our profile function we wouldn't know
when those frames were popped and it was no longer safe to reference
them.
After this change, we are able to detect when our profile function is
deregistered (either because a new one has been installed or because the
thread state the profile function was registered with is dying). This
gives us a hook to invalidate our cached frames to prevent this
use-after-free bug.

Handle our profile function getting uninstalled

---

src/memray/_memray/tracking_api.cpp
tests/integration/test_tracing.py

Up until now we've been greedily capturing the line number of each
Python frame as we first encounter it, but this is unnecessarily
inefficient. Since we've already been assuming that it's safe to call
`PyFrame_GetLineNumber` without the GIL held (and we'd already need to
change this code should that assumption become false in a future CPython
version), we can delay calculating the Python line number until we're
about to emit the frame. Since many frames are entered without ever
being emitted (because no allocation is performed under them), this
drastically reduces the number of calls to `PyFrame_GetLineNumber`,
which is a deceptively slow function.

Fetch line numbers for Python frames lazily

---

news/185.feature.rst
requirements-test.txt
setup.py
src/memray/_memray.pyi
src/memray/_memray.pyx
src/memray/_memray/hooks.cpp
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd
tests/integration/test_greenlet.py

Attempt to detect when the `greenlet` module is used (whether it has
already been imported at the point when tracking starts, or it gets
imported after tracking has started). If we discover that the `greenlet`
module is in use, register a callback to discover greenlet switch events
and react to them.  Unfortunately, this callback needs to be registered
once per thread, and the only place where we can reasonably register it
in a background thread is when our profile function is called, so we may
miss greenlet switches if they occur before any Python calls.
If we detect Greenlet, print a warning that this support is experimental.
Closes: #166

Detect the greenlet module and try to handle it

---

docs/index.rst
docs/native_mode.rst
docs/supported_environments.rst

Also document any known issues that can lead to incorrect, misleading,
or confusing stack traces.

docs: Document supported environments

---

.github/workflows/build_wheels.yml

As instructed by the action itself:
You are using "pypa/gh-action-pypi-publish@master". The "master" branch
of this project has been sunset and will not receive any updates, not
even security bug fixes. Please, make sure to use a supported version.
If you want to pin to v1 major version, use
"pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you
may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A
more general recommendation is to pin to exact tags or commit shas.
So we must pin to the v1 version of the action.

Ping to version 1 of the Pypi publish action

---

src/memray/_memray/tracking_api.cpp
tests/integration/test_processes.py

If we try to flush pending frames to disk in a forked process that has
been created without `follow_fork=True` we will miserably fail when
trying to get hold of the tracker and call
`Tracker::getTracker()->popFrame` or any other member function. We are
supposed to protect against this in the `forget_python_stack` function
but that's down by checking if the Tracker is deactivated or not by
calling `Tracker::isActive()`. Unfortunately, in `Tracker::childFork()`
we are missing a call to `Tracker::deactivate` if ``follow_fork`` has
not been passed.
As a consequence, we enter `emitPendingPushesAndPops` and hell goes
loose.
Closes: #195

Ensure the Tracker is deactivated after a fork without "follow_fork"

---

.github/workflows/build_wheels.yml
pyproject.toml
setup.py

- Revert "Don't build wheels on arm64 macOS for now"
- Build lz4 ourselves when building wheels

Build lz4 ourselves when building wheels

---

tests/integration/test_tracing.py

This line number is incorrect because two pull requests had a subtle conflict that wasn't caught by CI, because we don't enforce rebasing before the CI runs tests.

tests: Fix an incorrect line number

---

src/memray/_memray/compat.cpp
src/memray/_memray/frame_tree.h
src/memray/_memray/hooks.cpp
src/memray/_memray/logging.cpp
src/memray/_memray/macho_shenanigans.cpp
src/memray/_memray/macho_utils.h
src/memray/_memray/native_resolver.cpp
src/memray/_memray/native_resolver.h
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_reader.h
src/memray/_memray/record_writer.cpp
src/memray/_memray/sink.cpp
src/memray/_memray/sink.h
src/memray/_memray/snapshot.cpp
src/memray/_memray/source.cpp
src/memray/_memray/tracking_api.cpp

Update the source files to use C++ idioms, remove unused headers, remove
shadowing variables, remove empty declarations, make member functions
static when possible and fix small bugs due to calling virtual functions
in destructors.

Make some source cleanup

---

.gitignore
src/memray/_memray/CMakeLists.txt

Many IDES including CLion and VSCode automatically configure the project
if they find a valid CMakeLists.txt file they can work with. Adding this
file doesn't modify the build system but makes working with the native
part of memray much easier when using IDEs.

Add a CMakeLists.txt to build the extension as a static library

---

docs/transform.rst
src/memray/commands/transform.py
src/memray/reporters/transform.py
tests/unit/test_transform_reporter.py

When there are a lot of different allocations, some of the reporters that
we currently offer do not allow for a very granular inspection of the
data. This can happen for example when certain libraries like TensorFlow
or sklearn or pandas are imported as the number of allocations
goes easily to several thousand. In these situations, reporters like the
summary reporter are not helpful as the number of rows to display needs
to be really high and is not easy to analyze.
To allow other more specialized data analysis tools to work with the
data, add a new 'csv' output format to the 'transform' reporter that
will dump a comma-separated-value file with every allocation in the high
watermark as a row with columns representing different properties
of every allocation. The stack trace will be …

Add 'csv' format to the 'transform' reporter

---

news/251.bugfix
src/memray/_memray/records.h

When we need to register a new Python frame that we have not seen before
or when we need to get the ID of an existing Python frame, we use the
FrameCollection class that manages the collection of known Python
frames. The mutation of this data structure was previously protected by
the GIL as we only do these operations on the Python tracing function,
but since the introduction of lazy frame registering, now operations
over the FrameCollection can happen under the allocation/deallocation
hooks directly, and therefore access is now non synchronised.
This problem is still very difficult to trigger because the only
situation when a race will occur is when two threads compete to write
and read from the FrameCollection at the same time and for this to
happen at least one of these threads needs …

Ensure the access to the FrameCollection class is synchronised

---

docs/supported_environments.rst
news/194.feature
src/memray/_memray.pyx

Previously this warning would be printed each time a `Tracker` was constructed, which caused a lot of noise when `pytest-memray` was being used, since it creates one `Tracker` per pytest test. Now it will only be printed at most once per Python interpreter run.
Closes #194

Consider macOS to be fully supported

---

.github/workflows/build.yml
.github/workflows/build_wheels.yml
MANIFEST.in
pyproject.toml
setup.py
src/memray/_memray.pyi
src/memray/_memray.pyx
src/memray/_memray/CMakeLists.txt
src/memray/_memray/inject.cpp
src/memray/commands/__init__.py
src/memray/commands/_attach.gdb
src/memray/commands/_attach.lldb
src/memray/commands/attach.py
tests/integration/test_attach.py

Use a debugger (currently gdb or lldb) to inject code to initiate Memray tracking into an already-running process, provided that the process is running in an environment where `memray` can be imported.
Closes #218

Allow attaching Memray to a running process

---

src/memray/_memray/inject.cpp
src/memray/commands/_attach.gdb
src/memray/commands/_attach.lldb
src/memray/commands/attach.py
valgrind.supp

Previously we were returning a `const char*` pointer to a string literal, which we would then print in the debugger and check for in the `memray attach` code to ensure that it was printed. But, under some mysterious circumstances `gdb` could fail to print out the string that we've returned a pointer to, with "Address 0x7a1e7b90 out of bounds".
I don't really understand the root cause, but we can work around the issue by returning something simpler instead. We'll return just an int rather than a pointer to memory in the process we've attached to, and we'll make the debugger sessions either exit with an error code (gdb) or print a sentinel string we can recognize (lldb) if an error occurred.

attach: Return an int from the trampoline function

---

news/268.feature
src/memray/reporters/flamegraph.py
src/memray/reporters/templates/flamegraph.html
tests/unit/test_flamegraph_reporter.py

To reduce the noise of the import system frames, mark them as irrelevant
so they are hidden by default unless the checkbox to hide irrelevant
frames is not marked. Additionally, rename the checkbox from
"hide non-relevant" to "hide irrelevant" for clarity.

Mark frames from the import system as irrelevant

---

NEWS.rst

This was accidentally documented as 1.4.1.

docs: Fix changelog for 1.5.0 release

---

src/memray/_memray/inject.cpp

This could be used uninitialized if for some reason `getaddrinfo` fails
to return any interfaces. That shouldn't happen, but we should
initialize this anyway.

Fix an uninitialized variable

---

src/memray/_ipython/flamegraph.py

A new version of IPython adds annotations for `Magics`, so we need to update to avoid warnings about unnecessary `type: ignore` comments.
Additionally, I realized that our `parse_options` method is unintentionally overriding a method inherited from our base class. We could rename the method to avoid the collision, but since its body is only one line, let's just inline it into the caller.

Update the type annotations for our IPython magic

---

news/283.bugfix.rst
src/memray/commands/run.py
tests/unit/test_cli.py

We had always intended this to be supported, but the flag was not properly propagated from the command line to the tracker. Correct this, and add tests to prevent a regression.

Respect `--trace-python-allocators` in live mode

---

src/memray/_memray/tracking_api.cpp

This code was written to avoid an extra branch by unconditionally calling `popFrames` even if no frames need to be popped. When it was originally written that was a reasonable choice, because `popFrames` contained a loop and calling `popFrames(0)` wound up being a no-op because the loop condition was always false. That loop was later moved into the `RecordWriter`, and now calling `popFrames(0)` incurs an expensive mutex lock that we don't need to pay for, as well as a TLS fetch and a virtual method call.

Don't call Tracker::popFrames unnecessarily

---

src/memray/_memray_test_utils.pyx

We've been importing this declaration through a deprecated name.

tests: Fix Cython warning

---

src/memray/_memray.pyx
src/memray/_memray/frame_tree.h
src/memray/_memray/hooks.cpp
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_writer.cpp
src/memray/_memray/record_writer.h
src/memray/_memray/records.h
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd

In order to guarantee mutual exclusion between the tracker singleton being destroyed and allocation tracking that may be happening in other threads, switch from a fine grained locking model for the tracker to a coarse grained one where the same lock is used for all critical sections.
Closes: #288

Revamp tracker locking

---

src/memray/reporters/templates/base.html

We are inconsistently using decimal and binary multiples in different
places where we report sizes.

Use consistently binary multiples in the reporters

---

docs/python_allocators.rst
src/memray/_memray.pyx

We allow users to pass this value but we currently do not include it in
our public API documentation.
Closes: #253

Document ``trace_python_allocators`` in the memray API docs

---

.github/workflows/sanity-check.yml

We constantly forget to add news entries in Pull Requests and we need to
fix this after the Pull Requests are landed. With this action we can
easily automate the check so we can consciously decide to ignore if
needed.
Signed-off-by: Pablo Galindo <pablogsal@gmail.com>

Add a GitHub action to check for changelog files

---

benchmarks/benchmarking/plot.py
news/310.bugfix.1.rst
setup.py
src/memray/commands/_attach.gdb
src/memray/reporters/summary.py
src/memray/reporters/table.py
src/memray/reporters/transform.py
tests/integration/test_main.py
tests/integration/test_tracking.py
tests/unit/test_tui_reporter.py

There's [a bug (fixed in gdb 10.1)](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=da1df1db9ae43050c8de62e4842428ddda7eb509) with how gdb parses the "commands" command when reading from a script, which causes the commands to get associated only with the first breakpoint rather than all of the breakpoints we wanted them associated with.
Through sheer good luck, this bug doesn't affect the case when a range of breakpoint numbers is given, rather than a space separated list of breakpoint numbers, so we can switch to using a range to avoid the bug.
Closes #309

attach: Work around a bug in old gdb versions

---

news/311.bugfix.rst
src/memray/commands/attach.py

lldb on Linux appears to have a bug causing it to sometimes leave a process stopped at a breakpoint even after the debugger has detached. Defend against this by sending a `SIGCONT` signal to the process after the debugger attaches. If the process was already resumed then it will just ignore this spurious signal, but if lldb had left it stopped this will rescue it.
Relates-to: https://github.com/llvm/llvm-project/issues/60408.
Relates-to: #309

attach: Wake up the process after lldb detaches

---

news/308.feature.rst
src/vendor/libbacktrace/Makefile.am
src/vendor/libbacktrace/Makefile.in
src/vendor/libbacktrace/debuginfod_support.h
src/vendor/libbacktrace/elf.c
src/vendor/libbacktrace_2446c66076480ce07a6bd868badcbceb3eeecc2e_debuginfod_patch.diff
src/vendor/regenerate_libbacktrace.sh
valgrind.supp

- Add a new patch to libbacktrace to integrate with debuginfod
- Update the vendored libbacktrace files with the latest patch

Add a new patch to libbacktrace to integrate with debuginfod

---

.github/workflows/build.yml

The Python-based alpine image downloads and builds a Python executable
without symbols. This causes several tests to fail because we cannot
leverage the `python3-dbg`package that contains symbols for the
interpreter.
To fix this, use the vanilla Alpine docker image and also install the
`python3-dbg` package so we always have symbols available.

Use the vanilla Alpine image instead of the python-based one

---

docs/native_mode.rst

We have recently added integration with debuginfod servers but is
possible that some hosts do not have the client installed or the
environment variable in place.
To allow users to find all the information required to install and
configure debuginfod so it works with memray, add a small section to the
docs about it.

Add instructions to how to configure debuginfod in the documentation

---

src/memray/commands/common.py
src/memray/commands/flamegraph.py
src/memray/commands/table.py
src/memray/commands/transform.py
src/memray/reporters/__init__.py
src/memray/reporters/flamegraph.py
src/memray/reporters/table.py
src/memray/reporters/transform.py

This PR implements the cleanup of the `HighWatermarkCommand` interface that I promised when we were discussing ways to clean up #317 to pass the `TemporalAllocationRecord`'s through the layers more cleanly.
I think this is a huge improvement over what we've got. This is in a reviewable state, I'm only marking it as draft to remind us not to land it until we've landed #317 and rebased this on it.

Refactor `HighWatermarkCommand`

---

news/334.bugfix.rst
src/memray/_memray.pyx

In Python 3.11, due to the presence of non-entry frames we are hitting an assertion when constructing the hybrid stack.
for Python 3.10 and earlier, `len(hybrid_stack) == len(native_stack)`, which is why we've never seen this `assert hidx == -1` fail before. In 3.11 there are now non-entry frames, and `hybrid_stack` is longer than `native_stack` by the number of non-entry frames in the Python stack. If we fail to recognize a `_PyEval_EvalFrameDefault` call in Python 3.10 and earlier it only causes us to fill a native frame into `hybrid_stack` instead of a Python frame, but from 3.11 on it _also_ causes us to totally fail to insert any non-entry Python frames that were evaluated by that call to `_PyEval_EvalFrameDefault`, meaning we write fewer total entries into `hybrid_stack` than we …

Handle missing eval symbols in the hybrid stack with non entry frames

---

docs/flamegraph.rst

This section was written for flame graphs (our old default) rather than for icicle graphs (our new default), and so all of the top/bottom and above/below relationships are inverted.

docs: Fix "Interpreting flame graphs" section

---

news/344.bugfix.rst
src/memray/_ipython/flamegraph.py
src/memray/_memray.pyx

This applies to:
- progress bar text status
- jupyter magic %%memray_flamegraph output filename
*Issue number of the reported bug or feature request: #343*
I changed the color blue to cyan for a few text outputs to improve readability in dark themes.
The screenshot above shows good readability of the cyan text in both light and dark themes, and uses a color number below 16, so it displays properly in terminals with 16 colors.
Closes: #343

Improve text readability in jupyterlab dark theme

---

.pre-commit-config.yaml
CONTRIBUTING.md
MANIFEST.in
README.md
requirements-extra.txt
src/memray/_memray_test_utils.pyx

*Issue number of the reported bug or feature request: closes #355*
- Added pre-commit to extra requirements
- Created the `.pre-commit-config.yaml` file
- Updated contributing instructions on enabling pre-commit for local development
- Fixed issues in various files.
1. Installed pre-commit and set it up. All commits in this PR used the checks.
2. Ran all hooks against all files: `pre-commit run --files *`
I also added some pre-commit hooks that I like to work. These are in the top two sections of the YAML file.

Add pre-commit setup

---

docs/Makefile
docs/run.rst

Closes: #348
Runs sphinx in nitpicky mode
Fixes one error
sphinx build completes with no errors. Affected `html` file preview looks good.

Run sphinx in nitpicky mode

---

Makefile

*Issue number of the reported bug or feature request: #353 *
Delete only the following:
- `_test_utils`
- `_memray`
- `_inject`
- `build/` dir
To make sure that the virtualenv is working after running `make clean`, I did the following,
- Installed some packages in the virtualenv
- Start the interpreter and import a few modules
Closes #353

Only delete the *.so files that we create

---

.github/workflows/news-check.yml
.github/workflows/sanity-check.yml

- Separate the check for a news entry into its own action to apply only to `src/*` files
- Clean up `sanity-check.yml` workflow file
This PR will trigger the `sanity-check.yml` workflow file (which will now pass since there is no need for the `skip news` label), but not the `news-check.yml` workflow file since there are no changes to `src/memray/*`.

ci: Only check for news entries if src/ changed 

---

.github/workflows/build.yml
.pre-commit-config.yaml
Makefile
requirements-extra.txt
src/memray/_memray/alloc.h
src/memray/_memray/elf_utils.h
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_writer.cpp

*Issue number of the reported bug or feature request: closes https://github.com/bloomberg/memray/issues/360*
- Add `check-manifest` and `clang-format` to pre-commit setup (removing from `make`)
- Remove intermediary `make` commands
- Clean up `Makefile` and C files found during linting
- Configure pre-push hook to run in CI
- Remove extra requirements absorbed into pre-commit
Reinstalled the hooks to allow for pre-commit and pre-push hooks. Running `pre-commit run --all-files` runs in the pre-commit stage so all but `check-manifest`. Running `pre-commit run --all-files --hook-stage pre-push` only runs `check-manifest`.

Streamline linting processes

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

Issue number of the reported bug or feature request: #346 
- Removed pre-commit check for flake8
- Removed setup.cfg (flake8 config)
- Added a pre-commit check for `ruff` that covers flake8 checks and isort for Python files (.py and .pyi)
- Prevented isort pre-commit check from running on Python files
- Verified that ruff is fixing import order in .py and .pyi files (tested by introducing wrong order)
- Verified that ruff is fixing flake8 rules (tested by introducing unused import)
Some `isort` options are not supported by `ruff`.
Option `multi_line_output = 3` (break multiple imports in multiple lines using parenthesis) is not supported by ruff. The default behavior is the same as `multi_line_output = 7` (all imports …

Replace flake8 and isort

---

README.md
tests/unit/test_flamegraph_reporter.py
tests/unit/test_frame_tools.py
tests/unit/test_tree_reporter.py

*Issue number of the reported bug or feature request:  no issue*
- Use the generic path prefix /src for python in the unit tests that are mocking stack frames
- Add note in the README about MacOS deployment target
- pre-commit hooks
- make dev-install pycoverage
None

In unit test mocks, use generic path for python interpreter

---

.pre-commit-config.yaml

closes #347 
Add sphinx-lint pre-commit hook.
Introduced some issues into `.rst` files, then ran `pre-commit run --all-files`.

Add sphinx-lint pre-commit hook

---

.pre-commit-config.yaml

*Issue number of the reported bug or feature request: #349*
* Added rstcheck pre-commit hook to validate reStructuredText for news fragments.
1. Created rST files in the news directory, both valid and invalid. Some good examples for invalid rST are found in the [rstcheck README](https://github.com/rstcheck/rstcheck/blob/main/README.rst).
2. Staged the files and ran pre-commit. Errors should pop up for the invalid files. Unstaging the invalid files should allow everything to pass.
Closes #349

Add pre-commit hook for rstcheck

---

.github/workflows/build_wheels.yml
news/379.feature.rst
pyproject.toml
src/memray/_memray/hooks.cpp

#352 Set up CI to build and test musl libc wheels
Enable musl builds in the pyproject file. Dependencies for memray are supplied using comparable libraries from the Alpine main repository.
Running against GitHub actions is producing long build times. Further changes may be necessary.

Build musl x86-64 wheels

---

requirements-docs.txt
requirements-test.txt
setup.py

This works around a packaging bug in IPython 8.13: it drops support for Python 3.8, but still declares support for 3.8 in its `python_requires`, so `pip` installs the new version even for Python versions that don't support it.
See https://github.com/ipython/ipython/issues/14053

Work around an IPython packaging bug

---

requirements-docs.txt
requirements-test.txt
setup.py

This reverts commit 62fb9ad15a8456bc356cbc3ba42e33c6299eafa5. This is no longer necessary now that IPython upstream has yanked the release which incorrectly asserted it was compatible with 3.8.
Reverts #380

Drop pins to old IPython versions

---

.github/workflows/coverage.yml
Makefile

Issue number of the reported bug or feature request: #354 
This change will calculate C++ coverage in CI and upload the result to CodeCov. 
I tested on a personal fork of the project using appropriate secrets for personal CodeCov. 
Example PR: https://github.com/apurvakhatri/memray/pull/3

Publish Cppcoverage report in CI to Codecov

---

src/memray/reporters/assets/flamegraph_common.js
src/memray/reporters/templates/__init__.py
src/memray/reporters/templates/flamegraph.html
src/memray/reporters/templates/table.html
src/memray/reporters/templates/temporal_flamegraph.html

To make debugging of the generated javascript possible, we need to allow
to set `minimize: false` in the webpack.config.js file. Unfortunately
this has some problems:
* The non-minimized javascript templates includes some stuff that causes
jinja2 to freak out because it tries to interpolate the contents.
* The order of declaration of some classes is wrong and it fails to
create some objects at import time.
To help with this, add a new globally available function in the jinja
templates that allows us to include files without interpolating them and
fix the order-of-definition problems.

Allow to create non-minimized javascript files

---

pyproject.toml

If you provide multiple commands, `cibuildwheel` naively stitches them together into one shell command by concatenating them with `&&` in between. That changes the meaning of a shell `||` (it winds up running if a completely unrelated command fails).
Fix this by switching from `||` to an `if` statement.

Fix cibuildwheel `before-all` configuration

---

src/memray/_memray/tracking_api.cpp
src/memray/_memray_test_utils.pyx

A private Cython module used by our test suite still asks Cython to enable tracing and profiling support, even though we no longer need or make use of the artificial frames it supports (in fact, we deliberately detect and ignore these artificial frames).
Tell Cython to stop producing them. This lets Memray build on Python 3.12, for which Cython does not yet support profiling or tracing.

Drop Cython tracing from tests

---

.github/workflows/build_wheels.yml
pyproject.toml

Seems that cibuildwheel now allows building aarch64 wheels, so we should
try to distribute these as well.

Build also aarch64 wheels

---

README.md
news/420.feature.rst
src/memray/commands/__init__.py

*Issue number of the reported bug or feature request: #417 *
In order for memray to display its own version, I have added an argument to basic parser. Since it is added as an option rather than positional argument, only the init file was modified. Further, README has been updated on how to use the option. 
The command "memray --version" or "memray -V" successfully ran on my system (MacOS).
-

Support added for memray --version & -V

---

news/425.bugfix.rst
src/memray/_memray_test_utils.pyx

Correct signature of _pthread_worker

---

.github/workflows/build.yml
.github/workflows/coverage.yml
Makefile
tests/integration/test_api.py
tests/integration/test_extensions.py
tests/integration/test_processes.py
tests/integration/test_tracing.py
tests/integration/test_tracking.py
tests/unit/test_reader.py
tests/unit/test_stats_reporter.py

*Issue number of the reported bug or feature request: #351 *
The changes are - Python coverage report is generated & published to Codecov. Further, The report is analyzed & pragma no cover is added to increase test coverage.
I tested on a personal fork of the project using appropriate secrets for personal CodeCov.
In order to publish python coverage to codecov build.yml had to be modified. During build the python coverage had to be performed using the development dependencies on ubuntu-latest & alpine linux container (Line 67 & 101 of build.yml respectively). This part of the build was failing as the systems were lacing lcov. Therefore lcov was added using apt-get & apk add for ubuntu & alpine respectively. Further, …

Increase Python Coverage

---

news/433.bugfix.rst
src/memray/_memray/hooks.cpp

This prevents reentrancy if one hooked function calls into another. For instance, the jemalloc implementation of `malloc` calls into `mmap` while holding a lock, and our `mmap` hook calls `malloc`, so we must prevent our `mmap` hook from running beneath our `malloc` hook.
Closes #336

Set our recursion guard in all hooks

---

.github/workflows/build_wheels.yml

We switched from building our Linux wheels from a repo clone to building them from a build sdist, but we missed making the same change for building our macOS wheels.

Build macOS wheels from the sdist

---

.github/workflows/build.yml
.github/workflows/build_wheels.yml

An update of #223, rebased and PR'd from a branch instead of a fork so that it can (hopefully) request write permissions for the job that needs to publish the docs...

ci: Automatically publish docs for new releases

---

.github/workflows/build_wheels.yml

Python 3.12 is now ABI stable, so we should publish wheels for it.

ci: Allow publishing Python 3.12 wheels

---

src/memray/commands/common.py
src/memray/reporters/assets/flamegraph_common.js
src/memray/reporters/assets/temporal_flamegraph.js
src/memray/reporters/flamegraph.py
src/memray/reporters/templates/base.html
src/memray/reporters/templates/temporal_flamegraph.html

Temporal inverted flame graph

---

news/455.feature.rst
src/memray/commands/attach.py
tests/integration/test_attach.py
tests/unit/test_attach.py

Added --aggregate option which allows user to request aggregated mode for in-memory aggregation.

Added --aggregate option to attach

---

.github/workflows/build_wheels.yml
.github/workflows/coverage.yml
docs/conf.py
src/memray/_ipython/flamegraph.py
src/memray/commands/__init__.py
src/memray/commands/attach.py
src/memray/commands/run.py

Before adding a `description=` to our `ArgumentParser`'s:
```text
$ memray parse --help
usage: memray parse [-h] results
positional arguments:
results     Results of the tracker run
options:
-h, --help  show this help message and exit
Please submit feedback, ideas, and bug reports by filing a new issue at https://github.com/bloomberg/memray/issues
```
After:
```text
$ memray parse --help
usage: memray parse [-h] results
Debug a results file by parsing and printing each record in it
positional arguments:
results     Results of the tracker run
options:
-h, --help  show this help message and exit
Please submit feedback, ideas, and bug reports by filing a new issue at https://github.com/bloomberg/memray/issues
```
Before setting `COLUMNS` in our `docs/conf.py`:
After:

Miscellaneous improvements to our documentation and help messages

---

news/473.bugfix.rst
src/memray/_memray/native_resolver.cpp
src/memray/_memray/native_resolver.h

`libbacktrace` gives us no way to free a `backtrace_state*` once it's
been created, so it's in our best interest to create as few of them as
possible. Rather than having one cache of `backtrace_state*` per opened
capture file, have a global cache of `backtrace_state*` (protected by
a global mutex).
Closes: #472

Avoid creating more `backtrace_state*` than needed

---

pyproject.toml

Now that we use `noexcept` in some Cython functions signatures, we can no longer support Cython versions prior to 0.29.31.

Declare our minimum supported Cython version

---

docs/attach.rst
news/458.feature.1.rst
news/458.feature.rst
src/memray/commands/__init__.py
src/memray/commands/attach.py
tests/integration/test_attach.py
tests/unit/test_attach.py

Letting memray attach supports deactivating an attached tracker manually, or after a specified heap size is reached, or after a specified time limit has elapsed.

Added new commands to memray attach

---

Dockerfile

Image debian:latest contains python3.11 so "docker build" returns error:
> [3/8] RUN python3.9 -m venv "/venv":
0.349 /bin/sh: 1: python3.9: not found
python3.9 is installed in Debian Bullseye release.

Fix Dockerfile - python3.9

---

.github/workflows/coverage.yml

As Matt [said for python-comdb2](https://github.com/bloomberg/python-comdb2/pull/45#discussion_r1367462028): let's not do this.

Always run required CI checks

---

news/490.bugfix.rst
src/memray/commands/_attach.lldb
src/memray/commands/attach.py

When using lldb in macOS, the output of lldb is slighly different and we
are not properly matching that is what we expect. To avoid having to
rely on weird hacks to not detect the actual command we issue, filter
the output to not contain the lines that have the debugger promt to only
check against the actual debugger output. This simplifies the check and
provides an easier way to do assert that we are in the situation we
expect.
Add any other context about your …

Fix debugger output parsing in attach command

---

news/490.bugfix.rst

And add a little bit more detail, since we now know this issue isn't specific to macOS.

news: Fix a misspelled news entry

---

news/492.feature.rst
src/memray/_memray.pyx
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_writer.cpp
src/memray/_memray/record_writer.h
src/memray/_memray/record_writer.pxd
src/memray/_memray/records.h
src/memray/_memray/records.pxd
src/memray/_metadata.py
src/memray/reporters/templates/base.html
tests/integration/test_main.py
tests/unit/test_stats_reporter.py

We warn when generating a leaks report when pymalloc is in use, because
the memory held by pymalloc would appear to us as a leak when it has
actually just been set aside for future use.
But, when `--trace-python-allocators` is used, we do have visibility
into whether the memory has set aside for future use, and so we don't
need to show this warning in that case.

Disable leaks warning if tracing Python allocators

---

src/memray/_memray.pyx

Refresh the progress bars on exit

---

src/memray/reporters/tui.py
tests/unit/test_tui_reporter.py

When the TUI shows a command line that indicates that Memray is running (either a command named `memray` or a file named `memray/__main__.py` as the first argument), shorten this to just "memray" to save room for more valuable information.

Abbreviate Memray's path displayed in the TUI

---

.github/workflows/coverage.yml
pyproject.toml
requirements-test.txt
setup.py

Using pkg-config we can get automatically the build flags in MacOS
and Linux and this doesn't require the user to manually modify CFLAGS
just to build the extension.
Signed-off-by: Pablo Galindo <pablogsal@gmail.com>

Leverage pkg-config in setup.py

---

.pre-commit-config.yaml
pyproject.toml
src/memray/reporters/stats.py
src/memray/reporters/table.py
src/memray/reporters/tui.py
tests/integration/test_main.py
tests/integration/test_tracking.py
tests/unit/test_stats_reporter.py

Make minor performance improvements using [ruff](https://docs.astral.sh/ruff/) rules [C4](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4) and [PERF](https://docs.astral.sh/ruff/rules/#perflint-perf).
```
9	PERF102	[*] When using only the keys of a dict use the `keys()` method
9	PERF401	[ ] Use a list comprehension to create a transformed list
4	C401   	[*] Unnecessary generator (rewrite as a `set` comprehension)
4	C402   	[*] Unnecessary generator (rewrite as a `dict` comprehension)
4	C408   	[*] Unnecessary `dict` call (rewrite as a literal)
3	C405   	[*] Unnecessary `list` literal (rewrite as a `set` literal)
1	C416   	[*] …
```

Make minor performance improvements using ruff rules C4 and PERF

---

.github/workflows/build.yml
.pre-commit-config.yaml
docs/_static/css/custom.css
src/memray/reporters/assets/common.test.js
src/memray/reporters/assets/temporal_flamegraph.js

* #500
% `pre-commit autoupdate`
% `pre-commit run --all-files`

pre-commit autoupdate

---

docs/_templates/index.html

This PR fixes a grammatical error that's immediately visible on the Memray landing page.

Update marketing copy

---

.github/workflows/build.yml

Coverage.py sometimes reports events with the line number as 0. We need to ignore these.

ci: Fix coverage reporting on Alpine

---

.github/workflows/build_wheels.yml

Another approach for #513 where we use one artifact per OS + architecture instead of one per wheel.

Update `upload-artifact` and `download-artifact`: one artifact per OS + arch + platform tag series

---

setup.py

`memray tree` already uses features that require this version (`TextArea` was introduced in Textual 0.38, and `TextArea.text` gained a setter in Textual 0.41).
Correct our package metadata to accurately reflect our supported versions of the Textual dependency.
See #518

Depend on Textual >= 0.41

---

src/memray/_memray/snapshot.h

Without this the build fails on the upcoming Fedora Linux 40 release with:
```
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fexceptions -fexceptions -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -D_FILE_OFFSET_BITS=64 -DUSE_MEMRAY_TLS_MODEL=1 -Isrc/memray/_memray -Isrc -I/builddir/build/BUILD/memray-1.11.0/src/vendor/libbacktrace/install/include …
```

Add missing include

---

docs/jupyter_magic.rst
news/538.feature.1.rst
news/538.feature.2.rst
src/memray/_ipython/flamegraph.py
tests/integration/test_ipython.py

IPython improvements

---

news/525.bugfix.rst
src/memray/_memray/elf_shenanigans.cpp
src/memray/_memray/hooks.cpp
src/memray/_memray/hooks.h
src/memray/_memray/macho_shenanigans.cpp
src/memray/commands/_attach.lldb
tests/integration/rpath_extension/ext.c
tests/integration/rpath_extension/setup.py
tests/integration/rpath_extension/sharedlibs/sharedlib.c
tests/integration/test_extensions.py

We need to override dlopen/dlclose to account for new shared libraries
being loaded in the process memory space. This is needed so we can
correctly track allocations in those libraries by overriding their PLT
entries and also so we can properly map the addresses of the symbols in
those libraries when we resolve later native traces. Unfortunately, we
can't just override dlopen directly because of the following edge case:
when a shared library dlopen's another by name (e.g.
dlopen("libfoo.so")), the dlopen call will honor the RPATH/RUNPATH of
the calling library if it's set. Some libraries set an RPATH/RUNPATH
based on $ORIGIN (the path of the calling library) to load dependencies
from a relative directory based on the location of the calling library.
This means that if we override dlopen, …

Override dlsym instead of dlopen to correctly honour RPATH/RUNPATHS

---

src/memray/_memray.pyx
src/memray/_memray_test_utils.pyx

This has been deprecated for a while. Let's switch to using runtime checks for things that can be checked at runtime, and inline C++ code with conditional compilation for things that need to be checked at compile time.

Stop using `IF` in our Cython code

---

news/552.bugfix.rst
src/memray/commands/run.py
tests/integration/test_main.py

Closes #551 
I struggled to write good tests for this, and while working on it I realized that at least one of the existing tests wasn't actually proving what it set out to prove, so I restructured the existing tests as well.

Fix `sys.path` manipulations for isolated mode

---

README.md

Every code block but one was preceded by either a colon or a period.

Fix typographical consistency in README

---

.github/workflows/build_wheels.yml

We can't get this for free from the manylinux2010 image, because support for it was dropped before Python 3.11 came out. We can spin up a container based on that image, install Python 3.11 and 3.12 in it, and then ask cibuildwheel to use it for building some wheels for us (and running `auditwheel repair` and tests).
We'll do it only for x86_64, not i686, since 64-bit is much more heavily used.

Publish manylinux2010 wheels for Python 3.11/3.12

---

Makefile
docs/Makefile
docs/conf.py
docs/manpage.rst

This man page will contain a small bit of prose explaining what Memray is and where to find the full documentation, followed by CLI usage information scraped from the `--help` of each of our subcommands. Distros can build the man page for any given version to include in distro packages of Memray.

docs: Allow producing a `memray.1` man page

---

src/memray/_memray.pyx
src/memray/_metadata.py
src/memray/commands/common.py
src/memray/commands/summary.py
src/memray/commands/tree.py
tests/unit/test_highwatermark_command.py
tests/unit/test_stats_reporter.py

Users tend to run memray over long running programs but they don't tend
to know about the --aggregated option, while most of the cases they
don't need the extra features that runnin with the default mode has.

Add a warning to promote --aggregated if files are too big

---

news/560.feature.rst
src/memray/_memray.pyx
src/memray/_metadata.py
tests/unit/test_reader.py
tests/unit/test_stats_reporter.py

To be able to filter allocations that happened only on the thread that
started the tracking, expose the main thread ID in the reader class.

Expose the main thread ID in the reader

---

.github/workflows/build_wheels.yml

This was broken when we added support for building manylinux2010 wheels for modern Python interpreters due to a misuse of the `include` configuration of the GitHub Actions matrix job.

Fix publication of x86_64 wheels

---

news/581.feature.rst
src/memray/reporters/tree.py
src/memray/reporters/tui.py

CTRL+z to suspend isn't enabled by default, but we can add it with a keybinding.
Closes: #559

Add a binding for Ctrl-Z to memray tree

---

news/597.bugfix.rst
src/memray/reporters/_textual_hacks.py
src/memray/reporters/tree.py
src/memray/reporters/tui.py

In Textual 0.61, `App.namespace_bindings` was removed in favor of `Screen.active_bindings`. Update our implementation of dynamically updating footer descriptions to work for both, since we still support Textual versions below 0.61.

Fix live updates to footers on Textual TUIs

---

.devcontainer/devcontainer.json
.gitignore
Dockerfile

Update our Dockerfile to the latest Debian stable, and add a devcontainer.json based on it, with our build and test dependencies installed.

Allow spinning a Memray environment up in codespaces

---

.github/workflows/build_wheels.yml
.github/workflows/docs.yml

I don't want to merge this PR, but letting CI run it will allow updated docs to be published.

Publish docs on every PR, not just releases

---

README.md

I am building from source using a fairly fresh Ubuntu installation so I am taking this opportunity to document some of the build dependencies in the readme.
Just a change in the readme.
I followed the build instructions from the readme iterating when I get a build error on 
```
python3 -m pip install -e . -r requirements-test.txt -r requirements-extra.txt
```

Add build requirements for ubuntu

---

docs/run.rst

*Issue number of the reported bug or feature request*: #598 
This adds some documentation about how to run memray in containers that get out of memory
I tested the scripted solution locally (but not in a container)
this is how the docs render ![image](https://github.com/bloomberg/memray/assets/2919865/1311a493-fe49-40a0-adab-24376fc04c48)

document how to handle container OOM

---

.github/workflows/build.yml
.github/workflows/coverage.yml
pyproject.toml
setup.py
src/vendor/libbacktrace/debuginfod_support.h
src/vendor/libbacktrace/elf.c
src/vendor/libbacktrace/macho.c
src/vendor/libbacktrace_2446c66076480ce07a6bd868badcbceb3eeecc2e_debuginfod_patch.diff
src/vendor/libbacktrace_2446c66076480ce07a6bd868badcbceb3eeecc2e_patch.diff

This allows us to guarantee that `libdebuginfod` is always available for every Memray install. Previously we were dependent upon using `dlopen` to find a copy of it already installed in the runtime environment.

Vendor libdebuginfod into our wheels

---

.github/workflows/docs.yml
Dockerfile
README.md

Fix docs building in CI. This was broken by #592, but wasn't noticed until the PR landed because the workflow only runs on main, not PRs.

Fix docs building in CI

---

src/memray/commands/_attach.gdb

`memray attach` needs to inject some custom code into the process it has
attached to. It does this by using `dlopen` and then calling a function
we control, but that can't be done just anywhere: we need to ensure
we're not currently in the middle of a call to `dlopen`, or in the
middle of a call to `malloc`, etc.
To work around this, we set a handful of breakpoints for known safe
(probably) places to call into our custom code, and load and call it
only when the breakpoint is hit.
Add 2 new breakpoints to our gdb script, on `PyCallable_Check` and
`PyError_CheckSignals`. Also, use `Py_AddPendingCall` to schedule a call
to `PyCallable_Check` on the main thread, in the hopes of triggering one
of our breakpoints to happen sooner.
For now, apply this only to our gdb script, and not to our lldb …

attach: Add gdb breakpoints for more safe entry points

---

news/615.bugfix.rst
src/memray/_memray/macho_shenanigans.cpp

The _dyld_shared_cache_contains_path is only available in macOS 11.0
or later. As we are compiling in a new system that's newer than 11.0 but
setting the deployment target to an older version, it's possible that
the _dyld_shared_cache_contains_path is not available in the target
platform and in that case we will segfault when calling it. It's also
possible that when compiling memray in an old system
_dyld_shared_cache_contains_path is not even prototyped in the headers.
To handle this, we change to fetch the function via a dlopen/dlsym approach
that will be generic in all macOS versions at the cost of an extra call
to dlopen the first time we interpose symbols.

Fix a segfault on macOS when _dyld_shared_cache_contains_path is not available

---

requirements-test.txt
setup.py

These two versions lead to a test suite deadlock. The problem has been reported upstream, so hopefully the next release contains a fix.
See https://github.com/Textualize/textual/issues/4634

ci: Avoid testing with buggy Textual versions

---

.github/workflows/build_wheels.yml
requirements-test.txt
setup.py
src/memray/_memray.pyx
src/memray/_memray/compat.cpp
src/memray/_memray/compat.h
src/memray/_memray/record_writer.cpp
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd

Note that wheels are not yet published, because Python 3.13 is not yet ABI stable.

Test with Python 3.13

---

.github/workflows/build_wheels.yml

Previously these were being built on macOS 11, but GitHub is dropping its macOS 11 runners. Upgrade to build these on macOS 13 instead (the latest version with free public Intel Mac runners). Because we leave `MACOSX_DEPLOYMENT_TARGET` set to 10.14, this should have no effect on the ABI of the built wheels.

ci: Build macOS x86_64 wheels on macOS 13

---

docs/tutorials/1.rst

*Issue number of the reported bug or feature request:N/A
Quick CR to fix a `typo` for "interperet" to "interpret" in the docs.
N/A
N/A

docs: Fix typo in tutorial 1

---

docs/tutorials/3.rst
docs/tutorials/exercise_3/lru_cache.py
docs/tutorials/solutions/exercise_3/lru_cache.py

The PR fixes the issues with the exercise 3 from the tutorial:
- There was an inconsistency between the code in the solution vs the exercise, as the exercise used `@classmethod` and the solution did not. Now that's been made consistent
- The 2nd solution did not lower the memory usage. Not sure why it was added there - the PR removes it
- An edit to the for consistency to utilise the same global variables instead of magic numbers

Tutorial: Fixes for Exercise 3

---

requirements-test.txt
setup.py
tests/conftest.py
tests/unit/test_tree_reporter.py
tests/unit/test_tui_reporter.py

Have our test suite check the version of Textual and pytest-textual-snapshot that it's running with, and automatically disable the Textual snapshot tests if we can determine statically that they will go on to fail. This is a better experience for 3rd party package maintainers and simplifies our handling of Python versions that Textual has already dropped support for. This doesn't negatively affect our CI, since we keep our dependencies live at head in CI.
Closes #654

tests: Skip snapshot tests if Textual is outdated

---

.github/ISSUE_TEMPLATE/---bug-report.yaml
.github/workflows/build_wheels.yml
docs/supported_environments.rst
news/658.feature.rst

Now that Python 3.13 is ABI stable, document that it is supported and begin to publish wheels for it.

Publish wheels for Python 3.13

---

src/vendor/libbacktrace-patches/0001-Expose-some-internal-functions-of-libbacktrace.patch
src/vendor/libbacktrace-patches/0002-Add-debuginfod-support-to-libbacktrace.patch
src/vendor/regenerate_libbacktrace.sh

This is based on #651 and should be rebased on main once that one lands.

Simplify updating libbacktrace

---

news/667.bugfix.rst
src/memray/_memray.pyx

The `Tracker.__enter__` and `Tracker.__exit` methods may wind up releasing the GIL, which allows another thread to see an intermediate state where the tracker is not fully installed. Add a lock, shared across all trackers, to serialize access to the global state that tracker installation and uninstallation writes to.
Closes #665

Lock around Tracker creation and destruction

---

.github/workflows/build_wheels.yml
pyproject.toml

Disable the `memray attach` tests in cibuildwheel. These tests have broken because of changes to the GitHub runners. The old debuggers being installed in the containers are not compatible with the new Linux kernel being used by the runners. Rather than spend a bunch of effort to get this working, we'll just disable these tests in those environments.
Note that we still exercising attaching with both debuggers in other workflows: the `test_with_coverage` workflow tests both gdb and lldb on glibc, and the `test_on_alpine` workflow tests both gdb and lldb on musl libc.
Additionally, ensure "Build and test wheels" can fail. We added the "Build and test wheels" job as a required check to our CI in order to avoid needing to list every possible matrix job as required, but this didn't actually …

Disable attach tests in cibuildwheel

---

news/549.bugfix.rst
src/memray/_memray/hooks.cpp
src/memray/_memray/hooks.h

This commit is just for backup on our main strategy of using dlinfo
instead of dlopen.

Try to respect RPATHS of calling dlopen modules with dlinfo

---

setup.py

Memray still supports Python 3.7, add the missing classifier for PyPI.
None.

Add Python 3.7 Trove classifier

---

README.md

Right now, clicking the badges takes you to the badge image.
Instead, link to a relevant webpage (like pytest-memray does).
Went to https://github.com/hugovk/memray/tree/readme-badge-links?tab=readme-ov-file and clicked 'em all.

README: Add links to badges

---

news/685.bugfix.rst
src/memray/_memray/elf_shenanigans.cpp
src/memray/_memray/linker_shenanigans.h

The fact that patching ourselves had not raised problems so far its
really an outstanding fact in this universe. Unfortunately seems that
with the latest toolchain + GCC there is something that causes memray to
point the d_original entry of the hooks pointing to itself, which should
never happen.
To fix this resiliently, avoid patching ourselves by getting our own
name in the extension module and then avoiding that shared object.
Closes: #662

Avoid patching symbols in the extension module

---

.github/workflows/news-check.yml

Until now we've been requiring every PR affect a file in the news/ directory or be labeled with `skip-news`. Also allow a PR to directly touch NEWS.rst instead.

ci: Don't require `skip-news` if NEWS.rst changes

---

.github/workflows/build.yml
Makefile
news/693.bugfix.rst
src/memray/_memray/macho_shenanigans.cpp

This commit addresses an issue with symbol resolution for malloc_type
functions on the latest macOS Sequoia. The problem arises due to changes
in how these functions are named in the dynamic symbol table of the
system libraries that are part of the linker cache like the ones that
contain the C++ runtime.
This fix ensures that Memray correctly intercepts and tracks allocations
made by malloc_type functions, fixing tracking allocations in the C++
runtime and other system libraries on macOS Sequoia.

Fix symbol resolution for malloc_type functions on macOS Sequoia

---

news/700.bugfix.rst
requirements-test.txt
setup.py
src/memray/_memray/tracking_api.cpp
tests/integration/test_greenlet.py

When greenlet tracking is enabled is possible that we run into a
situation where the function that recreates the Python stack in our TLS
variable after a greenlet switch is called **after** the profile
function has been deactivated. In this case, recreating the Python stack
is wrong as we are no longer tracking POP/PUSH events so when the stack
is inspected later nothing guarantees that the frames are still valid.

Protect against deregistered profile functions in greenlet switches

---

src/memray/_memray.pyi
src/memray/_metadata.py

This resolves https://github.com/bloomberg/memray/issues/704.
It is unclear why this error is specific to obscure configurations or
what is triggering it, but the overhead of fixing it is small anyhow.
We have been using this patch internally to resolve the issue.

Resolve a circular import error in obscure configuarations.

---

valgrind.supp

These are triggered by the importing the `readline` module, which is part of the Python standard library. Any leaks here aren't our responsibility to find or fix.

ci: Ignore memory leaks in `PyInit_readline`

---

.github/workflows/build_wheels.yml

Previously we were building them on x86-64 Ubuntu 24.04 runners in QEMU.

ci: Build aarch64 wheels on ARM Ubuntu 24.04

---

news/732.bugfix.rst
src/memray/_memray.pyx
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd

In the last macOS version (15.4) some change in the way Apple builds the
linker shared cache bundle has changed the layout to have a single
GOT-like entry for every PLT-like entry. This makes that if we patch a
single library we are patching all of them and our filtering of the
linker libraries is not working properly and memray crashes when the
TLS-releted calls recurse into our malloc calls.
To avoid this, use a pthread-based system for the RecursionGuard only on
macOS as we were already doing for the native unwinding TLS.
Describe the testing you have performed to ensure that the bug has been addressed, or that …

Switch the RecursionGuard to use pthread APIs

---

.github/workflows/build_wheels.yml
docs/_static/flamegraphs/.gitattributes
news/737.bugfix.rst
src/memray/_memray/source.cpp
tests/integration/test_ipython.py
tests/integration/test_socket.py

On ARM Linux, `char` is unsigned, unlike on all of our other platforms.
Since EOF is equal to `-1`, this means that we need to be careful to
avoid assuming that:
EOF == static_cast<char>(EOF)
On all of our other platforms that's true, but on aarch64 Linux machines
that compares `-1 == 255` instead. And when you want to loop until EOF
but don't recognize EOF, that's an infinite loop...
Also fix a bug where we could potentially return from extension code to
Python code without holding the GIL.
Also, have CI run pytest unbuffered and in verbose mode. This way, if
a crash occurs, we should at least be able to see what test was running
when things went wrong.
Also: Prevent IPython from writing history files in our tests.
We don't need the history features, so the extra thread managing
a sqlite …

Fix ARM Linux infinite loop in attach / live mode

---

src/memray/reporters/templates/classic_base.html
src/memray/reporters/templates/flamegraph.html
src/memray/reporters/templates/table.html

*Issue number of the reported bug or feature request: #712 *
Add a button to open the zoomed in RSS/Heap usage over time chart. Currently, it is not clear that clicking on the flamegraph opens this chart.
Tested locally by creating a table and flamegraph reporter using tutorial/exercise 2.

Add `Usage Over Time` button to topBar

---

.github/workflows/build_wheels.yml
docs/supported_environments.rst
news/742.removal.1.rst
news/742.removal.2.rst
pyproject.toml

Switch from musllinux_1_1 wheels to musllinux_1_2, and switch from manylinux2010 to manylinux2014.
Previously, we built manylinux2010 wheels for Python 3.7 through 3.12, and manylinux2014 wheels for Python 3.11 through 3.13.
Stop producing the manylinux2010 wheels. For each of the versions that previously had only manylinux2010 wheels, instead build manylinux2014 wheels.

Drop wheels for old platforms

---

src/memray/reporters/tui.py

Textual 3.3.0 introduced a race condition that leads to errors if an app's message queue is first accessed from a different thread. See https://github.com/Textualize/textual/issues/5845
This potentially affects the live mode TUI, which starts a background thread early on in app startup to monitor the memory usage reports coming in from the application being profiled and update the screen. We can work around this by starting our update thread a bit later in the startup process, at a point where the message queue will already have been accessed by the thread running the app.

Fix a race condition under Textual 3.3.0

---

.github/workflows/build_wheels.yml
requirements-test.txt
setup.py

Some of our tests fail because setuptools in not installed
in the virtual environment and we cannot build extensions.

Remove setuptools from rpath_extension test

---

news/803.bugfix.rst
src/memray/_memray.pyx
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h
src/memray/_memray/tracking_api.pxd

Memray needs to be able to report the current Python stack at the point where
a memory allocation occurs, but at that point the GIL may not be held, and so
we can't use the Python API to retrieve the current Python stack. We work
around this with a trick: we maintain a shadow stack of our own that tracks
what frames are on the Python stack, using a profile function similar to those
installed with `sys.setprofile`, and when an allocation occurs we consult our
shadow stack to see what Python frames exist.
That shadow stack holds borrowed references to Python frames, which means we
rely on the profile function for memory safety: we need it to tell us when
a Python frame is being popped off the stack, so that we don't try to reference
that frame after it has been freed. This leaves us with a …

Revise handling of removed profile functions

---

.github/workflows/build_wheels.yml
news/808.bugfix.rst
news/808.feature.rst
setup.py
src/memray/_memray.pyx
src/memray/_memray/compat.h
src/memray/_memray/inject.cpp
src/memray/_memray/record_reader.cpp
src/memray/_memray/record_writer.cpp
src/memray/_memray/records.h
src/memray/_memray/tracking_api.cpp
src/memray/commands/attach.py
src/memray/reporters/flamegraph.py
src/memray/reporters/templates/base.html
tests/integration/misbehaving_extension/misbehaving.cpp
tests/integration/multithreaded_extension/testext.cpp
tests/integration/native_extension/native_ext.c
tests/integration/rpath_extension/ext.c
tests/integration/test_attach.py
tests/integration/test_main.py
tests/integration/test_native_tracking.py
tests/integration/test_processes.py
tests/integration/test_tracking.py

- Handle incomplete files from process pools in tests. Our strategy for recovering from capture files that were not gracefully closed can lead to us losing up to 1 record per pool worker process.
- Declare that our distributed extension modules support free-threading.
- Declare that our test extension modules support free-threading.
- Build our inject extension against the stable ABI even for free-threaded Python versions.
- Ignore warnings printed by the target process in our `memray attach` tests.
- Update tests to handle `PYTHONMALLOC=malloc` not being supported in free-threaded builds.
- Update Memray to recognize and handle the `mimalloc` allocator used by free-threaded builds.
- Fix the flamegraph reporter to use the correct title for temporal reports with no allocations.
- Fix a …

Support free threading

---

news/823.bugfix.rst
src/memray/_memray/tracking_api.cpp
src/memray/_memray/tracking_api.h

Closes #820
When tracing starts in one thread, we use `PyThreadState_GetFrame` to
capture the current Python call stack in every other thread, so that we
can associate allocations made later in pre-existing threads with the
correct call stack.
Unfortunately, our approach doesn't play nicely with trace functions,
like those installed by Coverage. The stack we get by walking backwards
from `PyThreadState_GetFrame` sees call frames that a profile function
never sees (because `PyThreadState_GetFrame` gets frames that correspond
to calls to trace functions, but profile functions don't get called for
calls into trace functions). Because of this, we wind up referring to
frames even after they've been popped off the call stack. Because we're
holding borrowed references, this results in a …

Avoid holding frames captured by another thread
