- README.md
To help users understand how to install, build and use the tool, improve
the README.md file with a condensed version of some information from the
documentation and add build and install instructions. Additionally, add
some cool badges with PyPi stats.
> Improve the README.md file with extra information

- README.md
Updates the `pip` command to use the `python3 -m pip` style.
None, update to README only.
Following the good practice of using `pip`.
> Updates pip command to use python executable

- news/67.feature.rst
- src/memray/_memray.pyi
- src/memray/_memray.pyx
- src/memray/_memray/hooks.cpp
- src/memray/_memray/hooks.h
- src/memray/_memray/record_reader.cpp
- src/memray/_memray/record_reader.h
- src/memray/_memray/record_writer.h
- src/memray/_memray/records.h
- src/memray/_memray/tracking_api.cpp
- tests/integration/test_main.py
- tests/integration/test_native_tracking.py
- tests/integration/test_tracing.py
The net effect of all of these changes is a reduction in capture file size of approximately 90%, depending on the test being measured.
> Improve capture file space efficiency

- .github/workflows/build.yml
- setup.py
- src/memray/_memray/alloc.h
- src/memray/_memray/alloc.pxd
- src/memray/_memray/elf_shenanigans.cpp
- src/memray/_memray/elf_utils.h
- src/memray/_memray/hooks.cpp
- src/memray/_memray/hooks.h
- src/memray/_memray/tracking_api.cpp
- src/memray/_memray/tracking_api.h
- src/memray/_memray_test_utils.pyx
- tests/integration/misbehaving_extension/setup.py
- tests/integration/multithreaded_extension/setup.py
- tests/integration/multithreaded_extension/testext.cpp
- tests/integration/native_extension/setup.py
- tests/integration/test_native_tracking.py
- tests/integration/test_tracing.py
- tests/integration/test_tracking.py
> Add Alpine Linux support

- src/memray/_memray.pyi
- src/memray/_memray.pyx
- src/memray/_memray/alloc.h
- src/memray/_memray/alloc.pxd
- src/memray/_memray/hooks.cpp
- src/memray/_memray/hooks.h
- src/memray/_memray/record_reader.cpp
- src/memray/_memray_test_utils.pyx
- tests/integration/test_tracing.py
- tests/integration/test_tracking.py
> Hook `aligned_alloc`

- .github/dependabot.yml
This will ensure we don't forget to update the GHA packages we use in
the CI so we can benefit from bugfixes and security patches.
> Add dependabot to keep GHA up to date

- docs/stats.rst
*Issue number of the reported bug or feature request: none *
Fix a typo in the documentation of the  ``stats``.
Not needed.
Feel free to close this PR and fix it manually if this is the preferred approach. I could not open an issue for this fix since it does not correspond to any of the provided issue templates.
> Fix a typo in the `stats` documentation

- README.md
> readme: Fix broken link to pytest-memray docs

- README.md
> Make the Linux-only support more prominent in the README

- news/174.feature
- src/memray/_memray.pyx
- src/memray/_memray/tracking_api.cpp
- tests/integration/test_main.py
- Add NEWS entry for MacOS support
- Show a warning message when creating Tracker objects on MacOS
> Complete MacOS support with some warnings and NEWS entry

- tests/integration/test_tracing.py
If we only update line numbers on Python frame pushes and pops we'll get
this wrong, as the line number to be tracked changes in between two
allocations without us ever entering or exiting a Python function.
> tests: Test tracing in different lines of the root

- src/memray/_memray.pyi
- src/memray/_memray.pyx
- src/memray/_memray/native_resolver.cpp
- src/memray/_memray/native_resolver.h
- src/memray/_memray/native_resolver.pxd
- src/memray/commands/common.py
- src/memray/commands/summary.py
- src/memray/commands/tree.py
- tests/unit/test_highwatermark_command.py
> Show warning if symbols cannot be properly resolved

- docs/index.rst
- docs/jupyter_magic.rst
- news/237.feature.rst
- requirements-docs.txt
- requirements-test.txt
- setup.py
- src/memray/__init__.py
- src/memray/_ipython/__init__.py
- src/memray/_ipython/flamegraph.py
- tests/integration/test_ipython.py
Allowing memray to profile code in Jupyter Notebooks will help a lot of
users such as data scientist when using memray as this will shorten the
gap between their workflow and the way the run the profiler.
Closes: #215
> Allow memray to be executed as an IPython extension

- docs/run.rst
I found a typo while reading through your documentation.
*Issue number of related feature request: #253 *
> Fix typo in documentation

- docs/_static/css/custom.css
- docs/_templates/index.html
We have many publications about memray that we can showcase in the
landing page for better visibility.
> Add a section about "Memray in the media" in the landing page

- src/memray/_memray/tracking_api.cpp
- src/memray/_memray/tracking_api.h
- tests/integration/test_extensions.py
Up until now, each time we would unwind the native stack we would start with an empty vector, and then reserve enough space for it to hold the largest stack we had seen so far on the current thread. Instead of starting from scratch each time, save this vector in a thread-local variable so that we can reuse it from one unwind call to the next.
Note that our `RecursionGuard` prevents us from ever trying to unwind a second time on a thread before we've finished recording the first unwound stack. Note also that we don't record stack traces for deallocations, only allocations, so it won't be a problem that our deallocation hook will be called for this thread-local vector once the thread dies.
> Stop allocating a new vector for each unwind call

- src/memray/_memray.pyx
> Fix small doc issue in `Tracker`

- .github/ISSUE_TEMPLATE/---bug-report.yaml
> Typo in ISSUE_TEMPLATE

- .github/workflows/build.yml
- .github/workflows/build_wheels.yml
- Prevent the wheel action from running if the pull request doesn't include any files other than `CONTRIBUTING.md` and `docs/**`
- Clean up the YAML files touched with prettier
This uses the `paths-ignore` option in GitHub Actions (example [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths)).
> Selectively run GitHub Action

- CONTRIBUTING.md
- README.md
*Issue number of the reported bug or feature request: closes #357*
Copied the section on contribution licensing to CONTRIBUTING.md
N/A
N/A
> Add note about contribution licensing to CONTRIBUTING.md

- src/memray/_memray/snapshot.cpp
This makes use of more idiomatic C++ and is anecdotally faster.
> Use std::all_of instead of loop + boolean

- src/memray/commands/live.py
- src/memray/reporters/tui.py
Changed the controls of the live reporter view for pausing and unpausing to use the same button as a toggle.
> Change the controls of the live reporter

- news/449.bugfix.rst
- src/memray/commands/attach.py
> Preferring gdb over lldb on Linux

- docs/flamegraph.rst
Doc update to align with what appears to be a relatively new default flame graph orientation.
> docs: Make flame graph docs reflect icicle default

- docs/memory.rst
Used a more natural English idiom.
I read the sentence a number of times. :D
> docs: improve one preposition

- docs/flamegraph.rst
- docs/getting_started.rst
- docs/tutorials/1.rst
- docs/tutorials/2.rst
- docs/tutorials/3.rst
- docs/tutorials/additional_features.rst
- docs/tutorials/exercise_2/holding_onto_memory.py
- docs/tutorials/index.rst
Updates to memray tutorial docs.
*Issue number of the reported bug or feature request*: not related to an issue
Updated the 3 tutorial examples throughout by adding more code examples, adding more explainer text, and fixed typos. No additional examples added.
I've run the tutorial tests provided that continue to work. There were no code changes impacting tests.
No additional context
> docs: Updates to Memray tutorials

- news/801.feature.rst
- src/memray/_memray.pyx
- src/memray/_memray/compat.cpp
- src/memray/_memray/compat.h
- src/memray/_memray/frame_tree.h
- src/memray/_memray/record_reader.cpp
- src/memray/_memray/record_reader.h
- src/memray/_memray/record_reader.pxd
- src/memray/_memray/record_writer.cpp
- src/memray/_memray/record_writer.h
- src/memray/_memray/records.cpp
- src/memray/_memray/records.h
- src/memray/_memray/records.pxd
- src/memray/_memray/snapshot.pxd
- src/memray/_memray/tracking_api.cpp
- src/memray/_memray/tracking_api.h
- tests/integration/test_main.py
> Do not resolve line numbers at runtime
